:hardbreaks:

= 2023-01-08 モンステラ属の分類は古すぎる？

https://wikis.wheatonma.edu/rainforest/index.php?title=File:Monstera_tenuis_2013_1.jpg

https://wikis.wheatonma.edu/rainforest/index.php?title=File:Monstera_3.jpg

Monstera tenuisという巨大モンステラの幼い時の写真。後者のモンステラは何者か不明。

良い写真だったのでメモがてらブログを書いた。
ただ、この写真をみていてMonstera deliciosaって他のモンステラ属の種と似てないなと言う疑問が思い浮かんだ。

Monstera deliciosaのほかのモンステラ属と比べて変なところ

* 株が幼いときからワックスの効いた硬い葉を作る
* 株が幼い時から直立することができて木にペタッと張り付くような感じがない
* 大人になってからの生活の仕方が異様
* 大人になっても丸い葉のまんま
この疑問はモンステラ属に詳しくなるチャンスだと思い色々調べたものの全然情報が無い。

下記の1977年の物がよく知られているモンステラ属を分類する最後の試みに見える（中身は読んでいない）。

https://www.aroid.org/genera/monstera/Madison_Monstera_Rec.pdf

中身は読めていないが下記のような論文が存在するようで、英語の概要文に下記のように書いてあった。
> モンステラは、メソアメリカのサトイモ科で分類学的に最も理解されていない属です。

https://kerwa.ucr.ac.cr/handle/10669/80147

モンステラ属はアメリカ大陸にしかいないのでメソアメリカで最も理解されていないなら誰も理解してないんじゃないかと思った。
モンステラ属は人間にとって実用的な植物ではないとはいえ、フィロデンドロン属やアンスリウム属は多数の分類の試みがされていて、DNAなどを使った分類も行われているのになぜモンステラ属だけこんな状況なのか。

== 追記 2023-01-09

2004年にMonsteroideae亜科（Monstera属ではない）をDNAなどを活用した手法を使って分析している論文を見つけた。この中で4種類のMonstera属を選んで比較している。
特に言及が無いが、作られた系統樹を見るとMonstera deliciosaから他のモンステラ属への進化の支持率は割と低いようだった。

https://bsapubs.onlinelibrary.wiley.com/doi/full/10.3732/ajb.91.3.490