:hardbreaks:

= サトイモ科について詳しい本を紹介

サトイモ科に関連する本について紹介したい。
趣味程度に軽くサトイモ科に詳しくなろうと思ってもあまり手軽で読みやすい本が無いようだった。

== The Genera of Araceae （洋書）

[red]#*おすすめ*#

複数のサトイモ科植物の研究者がサトイモ科全体についてまとめたサトイモ研究の集大成と言える本。

ほとんどのサトイモ科植物に網羅的に解説することも目的としていて非常に幅広い。
サトイモ科植物の形態に非常に詳しく、あの変な器官は研究されていたんだという感動が多い。

1997年の本なので現在知られている最新の分類などを反映できていないところに注意。
PDFが論文検索サイトからダウンロードできる。

https://www.researchgate.net/publication/280387316_The_Genera_of_Araceae

== Aroid: Plants of the Arum Family （洋書）

[red]#*おすすめ*#

サトイモ科植物全体について網羅的に説明している本。生息環境ごとに紹介している。

網羅性や細かさでいうとThe Genera of Araceaeに軍配が上がるが、この本の良いところは生態や人間との関わりなどについて書いてあるところだと思う。
やはり、一般人としてはそういうカジュアルなところに興味が湧くので、この本は取り扱っている植物の幅広さと読み応えのバランスが取れた非常に素晴らしい本だと思う。

* 分類できるレベルで詳しくなりたいならThe Genera of Araceae
* サトイモ科について楽しみたいならAroid: Plants of the Arum Family

1990年頃の本なので一部古い分類になっている内容が存在する。

絶版していて値段が高騰している。
入手が難しい場合はInternet Archiveのデジタル図書館で借りる事ができる？（使用したことがない）

== サトイモ: 栽培から貯蔵、種芋生産まで 新特産シリーズ

[red]#*おすすめ*#

主にサトイモColocasia esculentaの栽培についての本。

サトイモは主要な農作物の1つなので農法書が色々あるんじゃないかと思ったもののそんなになく、現在も販売されているサトイモ専門の本はこれくらいだった。
（農家の人はどのようにサトイモ農業の知識を得ているのか少し疑問が湧いた）

この本では、序盤にサトイモ栽培の伝来の歴史や品種などについて軽く触れつつ、サトイモ栽培の詳細について、サトイモ栽培の単価を上げるための栽培方法などについて説明している。

//基本、サトイモは栄養繁殖で増やすためウイルスに一度感染すると小芋にも感染して収量が落ちる問題があるらしい。他に育て方によって小芋の成長のしかたが違う事など食用のサトイモ栽培をしなくても役に立つ情報が多く読み応えがある。
//TODO 未完成

https://www.amazon.co.jp/dp/454010134X

== コンニャク: 栽培から加工・販売まで 新特産シリーズ

コンニャク栽培について書かれた本。

コンニャクの歴史、品種、加工、栽培方法、病害虫対策、食べ方などについて書かれている。
コンニャクの芋はそのままで食べることはできず、加工する必要があるためそれらをに対する戦略についても説明をしている。

詳しいが同じシリーズのサトイモ本に比べると、農家の人じゃなければ有益ではない情報が多い。

https://www.amazon.co.jp/dp/4540041770

== タロイモは語る 今知られていること、伝えること

[red]#*ややおすすめ*#

主にColocasia esculentaについての本だが、様々なサトイモ科植物についても触れている。

タイトルが怪しげなのと、本の説明文から内容が読み取れなかったので大分警戒して買ったものの良い本だった。
世界各地のサトイモ科を主としたイモ系植物の栽培について研究した成果について書いた本だと思う。各地に生息する品種や食べられ方について触れている。

Colocasia esculenta以外にもCryrtospermaやMonsteraやシロカイウ（Colla）、スキスマトグロッティスなどのサトイモ科植物が食用のために栽培されていた事についての情報があり興味深い。

== 海を渡ったタロイモ

主にColocasia esculentaについての本。

イネは東アジア地域からやってきた作物と言われているが、イモはイネ以前に日本にやってきて当時の主食だった。イモは世界各地で今でも伝統的な栽培が行われている。
この本は、考古学的な観点でイモ栽培の文化がどのような関連があり広がっていったのか各地の文化を比較して分析した研究成果について解説している本（だと思う）。

イモという言葉、栽培方法、品種などはどこかから伝わってきたもので、同じような文化が伝わった地域、伝わらなかった地域があるということは、言われてみればそうだが全然木気にした事がなかったので新鮮に感じた。
ただ、内容が割と難しくあまり理解できなかった。

== 日本産テンナンショウ属図鑑

[red]#*ややおすすめ*#

日本のテンナンショウについて書かれた図鑑。テンナンショウの近縁属についても触れている。

序盤にテンナンショウの形態や特徴について説明して、その後各種テンナンショウの種類や特徴について書かれている。
テンナンショウに絞っているものの、サトイモ科植物の体の形態について詳しく書かれた日本語の書籍は他にないので貴重。

値段が高いのがネックなものの内容が面白いのでおすすめ。

== MIST LOVER

インドネシア周辺を中心に活動している植物収集家の方が作った自費出版本。
ブセファンドラ、スキスマトグロッティス、ホマロメナ、アグラオネマなどの品種カタログ的な本。

サトイモ科マニア的には現地の自生を撮った写真が興味深い。

== World Checklist & Bibliography of Araceae (and Acoraceae) （洋書）

英国のキュー王立植物園が発行している本。
属毎の形態的な特徴について触れつつ、研究者向けに属や種の分類に関連する論文を列挙している非常に網羅的な本なんじゃないかと思う。
趣味者なのでここまでのものはいらないかと思い買っていない。

多分下記がWeb版。
https://powo.science.kew.org/

同じく英国にはロンドン自然史博物館が作っているCATE Araceaeプロジェクトというものが存在する。
https://cate-araceae.myspecies.info/taxonomy/term/174

== WILD ARUM  （洋書）

積み本中。