:hardbreaks:
:sitetree-ignore:
:toc:
:toc-title: 目次

= サトイモ科植物の育て方


サトイモ科は幅広く種それぞれに得意不得意や注意点があったりするのですが、ざっくり育て方について説明します。
園芸の成績を上げるというよりは、なんとか毎年維持する程度のテクニックについて書かれた記事だと思ってください。

== 園芸カテゴリ

まず以下のカテゴリに分けます。
このカテゴリは分類の話ではなくどことなく育て方が似てるものを入れたざっくりしたものになっています。

* 芋系: Colocasia、カラジウム、カラー、Remusatia、テンナンショウ
* 根出草系: アンスリウム、園芸種のアグラオネマ、アロカシア、デフェンバキア、フィロデンドロン
* ツタ系（半着生）: ツル性の強いフィロデンドロン、モンステラ、ポトス（Epiprenum、Pothos）
* 渓流系: 渓流性のホマロメナ、スキスマトグロッティス、アヌビアス、ブセファンドラ

=== 芋系

芋系は地中に芋を作るサトイモ科植物を入れたカテゴリ。
サトイモ科園芸の中では難易度が高く、手間がかかるカテゴリになっています。

全期間調子が悪くなりがちのものもあるが、カラジウムなど調子の良い期間は手間いらずなものもあります。
ただ、どれの種でもなにかのきっかけで調子を崩した後に、連鎖的に状況が悪くなり最終的には芋が失われる事になりやすいです。

他にめんどくさいポイントを挙げると

* 休眠期がある。もしくは冬に休眠させる必要性がある場合がある
* 芋から芽を出す条件にうるさい事が多い
* 芋が腐る（軟腐病）
* 増やしづらい（バックアップの株を作りづらい）

=== この記事でカバーできていない事が明確な芋系の種

ミズバショウ、ザゼンソウ
Cryptosperma

=== 根出草系




== 土壌について

サトイモ科は保水力が高くて常に根に湿気がある状態を好むので基本的には保水力の高い土が良い。
そして、水が切れると枯れてしまう事が多いので、こまめに面倒を見られない場合は排水性も低めな土でも問題ない。
普通の園芸では排水性の低い、水気の多い土は腐ってしまう事があるため避けるべきだが、サトイモ科の場合は土中の細菌などへの耐性がある程度あるため問題ない場合が多い。

上記にはいくつか例外がある。
* 球茎を作る種: 水気の多い土を好むことが多いものの体調を崩したときにそのまま腐ってしまうことが多いので、排水性が高く保水力があまりない土で頻繁に水をやるほうが良いかもしれない。
* モンステラやポトス（Epipremnum aureum）といったツル性の強い種: 根を張る能力が低い場合があるので排水性が高い土の方が良いかもしれない。ただ、乾燥に強いので根が張れなくても水が切れなければ問題になり辛い。

=== 土壌のphについて

土壌のphが変わると植物が効率的に摂取できる栄養の種類が変わる。そのため、野生の植物では必要とする栄養に応じて生息地を変えている場合がある。
ただ、個人の園芸の場合いろんな栄養を与えられる事や肥料の予算などを考慮する必要がない。そのため、持論になってしまうが土のphにそこまで頓着しないような種については自生地が酸性だったとしてもアルカリ資材（石灰資材）多めの土にしたほうが良い。
（サトイモ(Colocasia esculenta)農業での栽培成績の情報を見る感じでそう考えている）

アルカリ寄り（石灰資材多め）の土には下記のメリットが存在する。

* 球茎で休眠するタイプの種は芽潰れしづらくなる
* アルカリ寄りの土は細菌などが繁殖しづらくなる
* 植物に有害なアルミニウムが溶けるのを防ぐ（アルミニウムは一般的な土によく含まれている）

逆に下記のような留意点が存在する

* カリウム、苦土、鉄、ホウ素が欠乏しやすい
// * HCO3
//QUOTE [http://inter-farm.co.jp/drph3/]

=== 配合の仕方

==== 陸生の種

フィロデンドロンやアンスリウム、クワズイモなどの陸生の物は下記の様な土がおすすめ。

* 赤玉土: 土。酸性寄り。できれば硬質の物が良い
* 腐葉土もしくはピートモス、バーク堆肥: サトイモ科は有機質が好き。酸性寄り
* 木炭チップ: 根腐れ防止。アルカリ資材
* 消石灰もしくは牡蠣殻、草木灰: アルカリ寄りにする石灰資材
* 苦土石灰: 石灰資材。アルカリ寄りの土壌は苦土=マグネシウム欠乏になりやすいので補う。
* バーミキュライト: 保水力、保肥力を上げる
* 小石やパーライト: 長期間の排水性を上げる
* 遅効性肥料

排水性を低くしたい場合は川砂を追加する。
乾燥寄りで育てる場合はヤシガラなどを追加すると保水力が低くなる。

==== 水辺で小型の種

ホマロメナ、スキスマトグロッティスなどの育て方について説明する。

水辺に住む植物は多くの場合で水苔だけで育てる事ができる。水苔には微量栄養素がほど良く含まれているためそれらに敏感な繊細な植物を育てる際に役立つ。

土で育てる場合は崩れにくく空気や水が循環できるようにする。
下記のような配合がおすすめ。

* 小粒赤玉土もしくは小粒鹿沼土、水槽用ソイル: 酸性寄り。なるべく固くて崩れにくいものを使う
* 小石やパーライト: 崩れにくく排水性や根張りを支える
* 遅効性肥料

==== 水辺で中大型の種

キルトスペルマ、アヌビアス、Orontiumなどの中型から大型の種。
これらについては何が良いのかはあまりわからない。逆に言うとなんでも良いのかもしれない。
セオリー通り行くと下記のような感じじゃないかと思う。

* 硬質赤玉土
* 木炭
* 腐葉土
* 肥料

水辺の植物は肥料を多く必要とする。
ちなみにアヌビアスは砂利をおすすめされる事が多い。ただそれが本当に良いのか疑問。

== 肥料について

土壌をアルカリ寄りにした場合は、微量栄養素が不足する可能性があるのでNPK以外も配合された物を与えたほうが良い。
例えば下記の様な組み合わせが良いんじゃないかと思う。

* ハイポネックス: 植物が一番必要とするNPK肥料
* メネデール: 意外と必要量が多く不足しがちな鉄分
* リキダス: 微量栄養素が色々入っている

水耕栽培用の肥料はNPKから微量栄養素まで揃っている事が多いのでこれを使うのもおすすめ。
* ハイポニカ

水辺で中大型の種については肥料切れしやすいので頻繁に睡蓮用の肥料を与えたほうが良い。

== 日光

直射日光を得意とする種はほとんどいないので程々の日差しで育てる。

== 霧吹き

湿度の高い環境を好む種類が多いことと、害虫対策になるの霧吹きを毎日する。
ポタポタ水が滴るくらい霧吹きを行ったほうが良い。

== 害虫

* アブラムシ
* アザミウマ（スリップス）
* ハダニ
* コバエ




