:hardbreaks:
:toc:
:toc-title: 目次
:sitetree-pariority-key: 2

= サトイモ科植物一覧

幅広いサトイモ科植物を見てみたいと思い属単位で片っ端から調べて見ました。
園芸、農業、アクアリウムの世界で有名な属は黄色で網掛けしました。
内容は適当な事を書いている場合があるかもしれません。

== Gymnostachydoideae亜科(ギムノスタキス亜科)

サトイモ科の中では最古に分化した亜科。

[%autowidth]
|===
|属|一般名|概要

|Gymnostachys属
|ジムノスタキス
|サトイモ科植物の中では異様な見た目をしていて外見はショウブ科植物によく似ている。
葉はショウブのように葉柄を持たず細長い。花はサトイモ科植物らしく仏炎苞を持つ。サトイモ科とショウブ科は近縁なためサトイモ科で古くに分化したGymnostachys属は2つの科の中間的な性質を持っているのだと思われる。
オーストラリアに生息し湿ったユーカリの森に生息する。
サトイモ科の中では非常に興味深い属だが園芸の世界ではほとんど見かける事がない。筑波実験植物園に展示されていることがある。
|===

== Orontioideae亜科(水芭蕉亜科)

ギムノスタキス亜科と姉妹亜科。水辺を好む種が多い。
サトイモ科ではそれなりに見られる性質だが、どの種も収縮性のある根を持っていてこの根を収縮させることで茎の位置などを調整する。
サトイモ科では成長点の先で花を咲かせると一度枝(シュート)が終了する。再び新しい枝が分岐して成長を再開する事になるが、Orontioideae亜科の種では花を咲かせた後の新しい枝が二枚下の葉の下と普通より低い位置から始まる特徴がある。

[%autowidth]
|===
|属|一般名|概要


|*Lysichiton属*
|ミズバショウ
スカンクキャベツ
|寒い地域の湿地に住み、大きな花を咲かせるサトイモ科植物。花が咲いた時と葉を切った時にひどい悪臭がするらしい。
東アジアからアメリカ大陸まで生息し、日本だと北海道から日本海沿岸にミズバショウが分布する。
暑さに弱いため通年飼育の難易度が高い。

|*Symplocarpus属*
|ザゼンソウ
|寒い地域の湿地に住み、大きな花を咲かせ、悪臭があるなどミズバショウ属に似るがSymplocarpus属では太い根を持つ特徴がある。
東アジアからアメリカ大陸まで生息し、日本だと北海道から日本海沿岸に分布する。
暑さに弱いため通年飼育の難易度が高い。

|Orontium属
|オロンティウム
オロンチウム
golden club
|水辺に住む抽水植物。水芭蕉亜科の中では珍しく温かい所でも育つ。様々な化石種が知られているが現存種はOrontium aquaticumのみ。
Orontium aquaticumは北アメリカ大陸東部に生息し池、川、湖などの湿地帯に生息する。仏炎苞が見当たらないサトイモ科でも珍しいタイプの花を咲かせる(花の下の方にある仏炎苞らしきものは仏炎苞とは違うとか)。
他の水芭蕉亜科の種と違い植物自体は臭くないが、睡蓮のように自身の腐った葉などで周りの土壌を作っていくタイプの植物のため成長するに連れてだんだん臭くなってくる。
稀だが公園の池に植えられたり、水中生活もできるのでアクアリウムで水草として使われることがある。

|===

== Lemnoideae亜科(ウキクサ亜科)

水上での浮遊生活に適応し、茎がなく葉と根だけという異様な姿の種で構成された亜科。言われなければ絶対にサトイモ科植物だと分からない見た目をしている。
この特殊な見た目からは裏腹に花を咲かせる能力を失っていない種が多く世界最小のクラスの花を咲かせる。ウキクサ亜科ではサリチル酸を使って育てることで開花を誘導することができる事が知られている。

ちなみにウキクサ亜科関連の日本語Wikipedia記事を2021年辺りに大幅加筆してくれた人がいて必見(英語版より充実している)。

[%autowidth]
|===
|属|一般名|概要

|*Spirodela属*
|ウキクサ
|流れの緩い水面で浮遊生活をしている植物。いわゆる浮き草。
日本中に生息しているウキクサ(Spirodela polyrhiza)はウキクサ亜科の中では大きい方で葉が1cmくらいになる場合がある。
世界中に生息している。
育てるのは簡単だが多少水流と肥料があったほうが良い。

|*Lemna属*
|アオウキクサ
|水槽にいつの間にか入って勝手に増えてる事で見かける機会が多いアオウキクサ(Lemna aoukikusa)が有名。水面ではなく水中生活に適応したヒンジモ(Lemna trisulca)というめずらしい形態の種もいる。
世界中に生息している。

|Landoltia属
|ヒメウキクサ
|流れの緩い水面で浮遊生活をしている植物。SpirodelaとLemnaの中間的な形質をもつ。
この属の種はヒメウキクサのみでアオウキクサに似てるがヒメウキクサは根が複数あるところが違う。よく見るとアオウキクサより葉が角ばっているような気がする。
日本では本州から九州にかけて生息している。

|*Wolffia属*
|ミジンコウキクサ
|流れの緩い水面で浮遊生活をしている植物。この属の種類はウキクサ亜科の中でも一層小さい(0.3–1.5 mm)。こんなに小さいにも関わらず花をつけるので世界最小の花をつける植物として知られる。ちなみにWolffia arrhizaは世界最小の維管束植物らしい。
一部地域では食用にされる。日本では栄養豊富で小さいためそのままミジンコウキクサを金魚やメダカの餌として使うことがある。
ミジンコウキクサは関東から沖縄まで見られる。花を一度見てみたい。

|Wolffiella属
|
|どういう特徴があるのか調べてもピンとしないが主に水中生活に適応した種で構成されている？
同じくウキクサ亜科で水中生活に適応したヒンジモとは異なる見た目をしている。
北アメリカ大陸に生息している種が多い。

|===

== Pothoideae亜科(アンスリウム亜科)

様々な暮らしをする種がいるが木の幹や岩などに着生したり登はんする生活に特化しているものが多い。
他のサトイモ科植物でも持っていることがあるが、Pothoideae亜科と姉妹亜科のMonsteroideae亜科ではジャニキュラム(geniculum)という器官をすべての種が持つ。これは葉柄と葉の間にある膨らんだ部分で光を効率的に集めるために葉の向きを変える用途で使われる。

[%autowidth]
|===
|属|一般名|概要

|*Anthurium属*
|アンスリウム
ベニウチワ
|観賞価値の高い花を咲かせることで園芸の世界では非常に有名。園芸種はハワイやオランダを中心に品種改良が盛ん。園芸種の他にも見ごたえのある葉を持った育てやすい種が大変多く観葉植物としても人気が高い。植物としての形態も根出草状だったりつる性だったり直立してみたりアリ植物がいたり多種多様。
約100くらいの種が知られていて推定では2000種位いると考えられている非常に多様な属。野生では殆どが木にくっついて暮らす着生植物。アンスリウム属はサトイモ科の中でも特に着生に特化して進化したランによく似た根を持っている特徴がある。

Anthuriumは種が多く形態も多様なのでいくつかのセクションに分類されている。いくつか紹介する。

*Calomystriumセクション*
マニアにはよく知られたAnthurium veitchiiなどの大型のアンスリウム種が多いセクション。
園芸の世界でよく知られるアンスリウムの原種Anthurium andraeanumもここのセクション。

*Cardiolonchiumセクション*
とにかく種類が多いセクション。
葉に白い葉脈がでることで知られるAnthurium crystallinum、Anthurium clarinervium、Anthurium magnificumなどはここに所属する。

*Urospadixセクション*
Anthurium vittariifoliumなど中細い葉が垂れ下がるアンスリウム種が多いセクション。
葉の裏表が割と似た形態になっていて見分けづらい特徴がある。

*Pachyneuriumセクション*
フーケリー(Anthurium Hookeri)や、anthurium ellipticumなどの葉をロゼット状に展開する種が多いセクション。
鳥の巣とよばれたりする非常に密度の高い根を地表に作ることで知られていてる。このアンスリウムはロゼットの中央にゴミを集めるのでそこから染み出した栄養を根で吸収するためにこのような根になっている。他に新芽が主脈を中心に巻かれている特徴がある。

*Dactylophylliumセクション*
Anthurium clavigerumやAnthurium polyschistumなど、三つ葉やそれ以上の子葉を掌状複葉で展開する種が多いセクション。茎が伸びるツル性が強いものが多い。

*Tetraspermiumセクション*
アンスリウムの中でも一番生息域の広いAnthurium Scandensが所属するセクション。
登はん性はほどほどで直立性がありでツバキのようなシッカリした葉をしていることが多いので樹木の幼木のように見える。

|Pedicellarum属
|
|一属一種。ボルネオ島に生息。
Pothoidium属やPothos属に近縁な属。Pothoidium属のように花の枝に複数の花を咲かせる。

|Pothos属
|ユズノハカズラ
ポトス?
|有名なポトス(Epipremnum属)とは関係がない。昔に誤ってここに分類されていた名残。
森林などに住みで他の木に登はんするツル性の植物。いくつかの種では葉柄が葉のように広がる特徴がある。
花を咲かせる際には枝の最後に咲かせる場合と、枝の途中で花用の枝を分岐させてそこに生成する場合がある。
中国、インド亜大陸、オーストラリア、東南アジアの島々に生息する。日本でも大東諸島に生息している。

|Pothoidium属
|
|花を咲かせる際には枝の最後に咲かせる場合と、枝の途中で花用の枝を分岐させてそこに生成する場合がある。Pothos属に似ているが一つの花用の枝に複数花が咲くところが違う。
唯一の種であるPothoidium lobbianumは葉柄が葉のように広がっている事で草姿がヤシの葉のように見える珍しい見た目をしている。
フィリピンの一部地域ではではかご加工や囲いなどの素材として市場に結構出回ると言うので(1920年の情報)現地では普遍種かも知れない？一度見てみたい。

|===

== Monsteroideae亜科(ホウライショウ亜科)

ポトス(Epipremum属)、モンステラ、スパスティフィラム、ラフィドフォラ、スキンダプサスなど園芸で有名な種が多い亜科。育てやすい種類が多い。
色々な暮らし方をする種がいるが他の他の木に登はんするつる植物生活に特化しているものが多い。
他のサトイモ科植物でも持っていることがあるが、Pothoideae亜科と姉妹亜科のMonsteroideae亜科ではジャニキュラム(geniculum)という器官をすべての種が持つ。これは葉柄と葉の間にある膨らんだ部分で光を効率的に集めるために葉の向きを変える用途で使われる。

[%autowidth]
|===
|属|一般名|概要

|Alloschemone属
|
|Rhodospatha属に似ていて姉妹群だと考えられている。

|Amydrium属
|アミドリウム
|Monstera属にとてもよく似た形態を持っているが、殆どの種が南アフリカに生息するモンステラ属と違いこちらは東南アジアに分布する。
木に着生する登はん性のあるツタ植物(半着生植物)。
Rhaphidophora属、Monstera属、Epipremnum属、Amydrium属、Anadendrum属は分類が混乱している可能性がある。

|Anadendrum属
|
|中国や東南アジアに生息する登はん性のあるツタ植物。
Rhaphidophora属、Monstera属、Epipremnum属、Amydrium属、Anadendrum属は分類が混乱している可能性がある。

|*Epipremnum属*
|エピプレムヌム
ハブカズラ
オウゴンカズラ
ポトス
|ポトスと言う名前で販売されるEpipremnum aureumは育てやすいため園芸での人気が非常に高く見かける機会が非常に多い。
世界中の熱帯気候に生息する。島嶼でのみ分布する種も多い。
物に登はんさせて成長させると茎が太くなり葉が大人の葉になる。大人の葉になると多くの種で葉に切れ込みや穴ができる。
Rhaphidophora属、Monstera属、Epipremnum属、Amydrium属、Anadendrum属は近縁で分類が混乱している可能性がある。

*Epipremnum aureum*
ポトスと言う名でよく販売されているがPothos属とは関係がない。
古くから熱帯性の島に多数帰化しているため長らく原産地不明だったがソシエテ諸島原産。非常に登はん力のあるツタ植物で場合によっては登はん先の植物を枯らしてしまうため絞め殺し植物として知られる。遺伝的障害により基本的に花が咲かず外部からシベレリンを散布しないと花が咲かない。

|Heteropsis属
|
|登攀性のあるツタ植物。葉の形と葉柄が短い特徴で枝全体が樹木の枝のように見える。
Heteropsis spruceana は、今日でもブラジルのアマゾニアでより糸やかごを編む材料の重要な供給源です
情報が少ない。
//TODO 要修正

|*Monstera属*
|モンステラ
ホウライショウ
|モンステラ属はサトイモ科の中でも特に有名な属。中でもMonstera deliciosaの葉は様々なところで南国風な植物のモチーフとしてよく使われている。園芸の世界でもよく知られた種類が多い。
熱帯アメリカ大陸の熱帯雨林の地面に生息する登はん性のあるツル植物。木に登っている最中などに茎が切れたりして乾燥を感じると長い根を地面に多数伸ばし始める。茎が切れることを想定しているためが非常に乾燥に強い。
地面から成長を始めるモンステラはジャングルの背の高い木の葉の隙間から差し込む光で光合成を行う。光はまだらに差し込むため広い範囲をカバーできる葉が有利になる。そこで、モンステラ属では葉に穴を開けて葉を作るコストを削減してその分大きく点水できるようにしていると言われている。
Rhaphidophora属、Monstera属、Epipremnum属、Amydrium属、Anadendrum属は近縁で分類が混乱している可能性がある。

|*Rhaphidophora属*
|ラフィドフォラ
ヒメモンステラ
ヒメハブカズラ
|葉に穴が空くヒメモンステラ(Rhaphidophora tetrasperma)が園芸の世界で有名。ヒメモンステラはモンステラに比べて幼葉の段階でも穴が開きやすいので、少ないスペースでモンステラのような雰囲気を楽しみたい場合に人気がある。
アフリカからオーストラリアにかけての熱帯域に生息する登はん性のあるツル植物。
Rhaphidophora属、Monstera属、Epipremnum属、Amydrium属、Anadendrum属は近縁で分類が混乱している可能性がある。

|Rhodospatha属
|ロドスパサ
|直立したり根出草だったりツル植物だったりととらえどころのない属。
幼葉に色がつく種類が存在しマニアに人気がある。ちなみに登攀させて大きく成長すると緑色の葉になる。
主に南アメリカに生息する。

|*Scindapsus属*
|スキンダプサス
シラフカズラ
|葉柄が短く登攀させると左右に重なり合うように葉が展開する姿に人気があり園芸でよく知られている。この時の葉は幼葉で大人になると葉柄が長く大きいMonsteroideae亜科でよく見る感じの葉を展開する。

|Stenospermation属
|
|根出草だったり直立したりする種で構成された属。着生することもできるがそこまで登はん性は強くない。
主に南アメリカに生息する。
//TODO 登はん性のとこが不明

|*Spathiphyllum属*
|スパスティフィラム
ササウチワ
|深緑色のササ状の葉と、美しい花を咲かせる事で鑑賞価値が高いので園芸の世界で有名。基本根出草状の植物だが時折Rhodospatha属のような感じで茎を伸ばし始める。
Aroideae亜科を除いた原始的なサトイモ科植物では、湿地以外の環境で根出草状の形態を取る種が少なくSpathiphyllum属とHolochlamys属とAnthurium属しか知られていない。
南アメリカと東南アジアの熱帯域に生息する。
育てやすく成長が早いのですぐ増える。とても耐陰性が高く薄暗いところでもよく成長する。

|Holochlamys属
|
|スパティフィラムに近い根出草。仏炎苞はスパティフィラムと違い肉穂花序を包み込むように咲く。花がスパティフィラムに比べて枯れやすい特徴がある。
Aroideae亜科を除いた原始的なサトイモ科植物では、湿地以外の環境で根出草状の形態を取る種が少なくSpathiphyllum属とHolochlamys属とAnthurium属しか知られていない。
ニューギニアとビスマルク諸島に生息する。

|===

== Lasioideae亜科(ラジア亜科)

殆どの種が湿地に住み葉柄や茎に棘を持つ。原産地周辺では食用にされる種がいくつか存在する。

[%autowidth]
|===
|属|一般名|概要

|Anaphyllopsis属
|
|仏炎苞の上方向に鋭く伸び上部が捻れる見た目の美しい花を咲かせる。
南アメリカの流れの緩い小川に生息する。

|Anaphyllum属
|
|花や葉などがAnaphyllopsis属に似る。
インドに生息する。

|*Cyrtosperma属*
|キルトスペルマ
|大きく成長してインパクトが有る見た目のため熱帯植物園では定番の植物。
サトイモ科ではよく見る矢じり状の葉を展開するが矢じりの先を基本的に空に向ける特徴がある。葉柄にはびっしりと棘がある。特に幼葉で葉脈が赤くなる。
東南アジアに太平洋のニューギニアを始めとする一部の島々に生息する。
栽培しやすい訳では無いが一部の種が東南アジアから中央太平洋にかけて芋が食用にされる。石灰土壌に強くツバルやキリバスなどのサンゴ環礁で作られた島では数少ない栽培可能な炭水化物として重宝されていた。


|Dracontioides属
|
|Urospatha属とDracontium属に近縁だが近縁種と異なり葉に穴が開く特徴がある。
湿地性の塊茎植物でブラジルに生息する。

|Dracontium属
|
|ラジア亜科の中では特異な形質を多数持つ属。
葉柄が長く模様があり、複葉を展開していて芋を持つことからコンニャクによく似ている。
ラジア亜科の中では花が小さく株に性別があるところが特徴になっている。
アメリカ大陸、西インド諸島に生息する。

|Lasia属
|ラジア
ラシア
ミズヤツデ
|主に湿地に住む匍匐性の植物。幼葉は矢じり状だが早い段階で深く避けたヤツデ風の葉を展開するようになる。茎と葉の裏にはびっしり棘が生える特徴がある。仏炎苞が細長くねじれていて見ごたえがある。芋を作らない。
湿地性のサトイモ科植物は多いがLasia属は直立した後に水面に垂れ下がる珍しい生活を行う。
インド・東南アジア・中国南部の湿地生で密集した群生を作る。現地では若葉を野菜として食用にする。

|Lasimorpha属
|
|主に湿地に住む匍匐性の植物。地下に根茎を伸ばす性質がある。Lasioideae亜科の中だと唯一アフリカに生息する。芋を作らない。
唯一の種のLasimorpha senegalensisは熱帯アフリカにの湿地で群生を作る。現地では若葉を食用にする他に薬として活用することもある。

|Podolasia属
|
|唯一の種のPodolasia stipitataは西マレーシアに生息する。

|Pycnospatha属
|
|生息地が離れているがDracontium属に近縁で姉妹属だと考えられている。
葉と芋がコンニャクに似ることから勘違いされやすい。
インドシナに生息して通常は落ち葉で覆われている砂利質の砂壌土や岩の間に生育する。
//TODO インドシナ?

|Urospatha属
|
|地下に芋を作る湿地生の植物。乾季には葉を落として休眠する。
中央アメリカから南アメリカの沼地、湿ったサバンナ、汽水域に生息する。

|===

== Zamioculcadoideae亜科

殆どのサトイモ科植物は一つの葉が1枚の単葉になっているか3枚程度の掌状の子葉を持つ形態だが、この亜科では基本的に羽状複葉や3回羽状複葉と言った生え方をする種で構成されている。
殆どの種で葉から根や芋を回復できる(葉軸を含んでなければならない)。

[%autowidth]
|===
|属|一般名|概要

|*Zamioculcas属*
|ザミオクルカス
|唯一の種であるZamioculcas zamiifoliaはツバキのような見た目の子葉を持ち観葉価値が高いことで有名。
サトイモ科植物とは思えない姿なものの根出草の植物の葉が子葉に分かれた(羽状複葉)と考えると理解しやすい。羽状複葉のサトイモ科植物は他にもいるがここまで異様な雰囲気の種は無いと思う。
東アフリカ出身で熱帯雨林の日陰や、砂の多い川岸の石の多い場所で主に暮らす。サトイモ科の観葉植物では珍しく加湿に弱い。そして乾燥に強い。

|Gonatopus属
|ゴナトプス
|1枚の葉が3回羽状複葉してたくさんの子葉を生やす。子葉の雰囲気がサトイモ科離れしていて低木植物のような雰囲気。
芋を作り基本一つの芋から1枚しか葉を出さない。Zamioculcadoideae亜科の中でも葉から根を回復する能力が高い特徴がある。
東アフリカ出身で熱帯雨林に住む。

|===

== Aroideae亜科(サトイモ亜科)

サトイモ科の中でも芋を持つ種が多い亜科。
サトイモ亜科だけ種類が多いので族毎に紹介

=== Aglaonemateae族 - Aroideae亜科(サトイモ亜科)

サトイモ亜科の中でもアグラオネマに近い属

[%autowidth]
|===
|属|一般名|概要

|*Aglaonema属*
|アグラオネマ
リョクチク
|主に中国などで古い時代から縁起の良い観葉植物として育てられてきた。現代では世界中で人気のある観葉植物として主にアメリカで栽培されている。
主に東南アジアに生息する
Dieffenbachia属はAglaonema属と似ているいる要素が多いので見間違われやすいが近縁ではない。分かりやすい見分け方は主脈に対して葉脈が10以下ならAglaonema属。20程度ならDieffenbachia属の可能性が高い。
//TODO 未完成

|Aglaodorum属
|
|アグラオネマに似るが緑色の果実を作るところが異なる。
干潟に生息しているらしい。ということは塩に耐性がある?
種子が落ちる前に発芽するところが珍しい。

|===

=== Ambrosineae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Ambrosina属
|
|Ambrosina bassiiが唯一の種。根出草でオオバコに似る姿をしている。花は他のサトイモ科植物では見られない見ない珍しい形をしている。
温暖な森林の地面や、開けた岩場に住む。

|===

=== Anubiadeae族 - Aroideae亜科(サトイモ亜科)

Geniculum

[%autowidth]
|===
|属|一般名|概要

|Anubias属
|アヌビアス
|育てやすくインパクトのある水草としてアクアリウムでは非常に有名。
アフリカ原産で熱帯雨林を流れる川の川岸や岩場に着生する半水生のツタ植物。茎は節が短いが匍匐したり着生したりする。
抽水もしくは水上で育てると肥料をガンガン消費してよく成長する。肥料が切れると全然成長しなくなる。

|===

=== Areae族 - Aroideae亜科(サトイモ亜科)

サトイモ科全体の基準になる模式属であるArumが所属するZantedeschieae族(主にカラー)に近い族。
花が臭い種類が多いが、これは主に腐った哺乳類にたかるハエを受粉のターゲットにしているためらしい。
比較的乾燥した地域に適応した種が多い。

[%autowidth]
|===
|属|一般名|概要

|*Arum属*
|アルム
|サトイモ科全体の基準になる模式属。そのためサトイモ科はarum familyと呼ばれたり、arumという名前がついている事が多い。
茎が伸びないカラー状によく似た生え方をする。大きな花を咲かせる。
ヨーロッパ、北アフリカ、西アジア原産で森林などの地面で暮らしている。

|Biarum属
|ビアルム
|一部の種では葉の構成が特殊で葉柄、葉の区別が曖昧になっている。
中東、ヨーロッパ、北アフリカなどに分布し、石灰岩の割れ目など過酷な環境に生息する。
果実は独特な色をしていて、背が低い位置に作られる事から周りの岩にカモフラージュしていると言われている。この状態だとあまり果実が分散できないはずだが、Biarum属の生息地は過酷な環境が多いため分散しても発芽できない可能性が高いためこのように進化したと考えられている。

|Dracunculus属
|
|偽茎で直立し、大きな花を咲かせる。
アメリカでは庭植えの園芸種として栽培が行われる。

|Eminium属
|
|葉が特徴的で深く切りこまれて細長い葉が説明し難い複雑さで捻れている。
トルコ、中東、中央アジアのサバンナやステップ気候の岩の多い斜面や砂地などに生息する。
栽培は難しい。

|Helicodiceros属
|dead horse arum
|唯一の種のHelicodiceros muscivorusは大きな花を咲かせる。この花はハエを誘うために死んだ哺乳類の花に擬態していると言われている。そのためHelicodiceros属の花は哺乳類のように毛が生えていて大分気持ち悪い。
花は周囲の温度に依存せずに熱を作ることができる特異性から研究が進んでいる。
この熱を作る形質は動物の死体の体温を再現していると言われ、花の臭い匂いも腐臭を再現するためのものだと考えられている。これらの事から哺乳類の死体を再現することに全力すぎるサトイモ科植物かもしれない。
葉はEminium属に似て複雑。

|Sauromatum属
|
|偽茎で直立する。花を除くとテンナンショウに姿がよく似ている。
生息域が広く　島嶼に広がり
//TODO 未完成

|Theriophonum属
|
|Typhoniumに似ている。芋を作る。
Typhoniumに比べると小さい特徴がある。

|Typhonium属
|リュウキュウハンゲ
|和名の通りニオイハンゲなど複葉を展開しないPinellia属(ハンゲ)の種に似ている。地中に芋を作る。
東南アジア、ギニア、オーストラリアに生息し、中でもリュウキュウハンゲは鹿児島から沖縄まで生息している。鹿児島では珍しいが　沖縄ではそこら中に生えているので雑草扱いらしい。

|===

=== Arisaemateae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Arisaema属
|テンナンショウ
マムシグサ
Cobra lily
|マムシのような美しい花の観賞価値が高く種類が多いことからマニアの間で人気がある。
地表から生えて背の高い独特な草姿をしている種が多い。自力で直立して背の高いサトイモ科植物というとコンニャクなどがあり姿が似ているが、Arisaema属は偽茎呼ばれる葉柄が茎状に折り重なった茎で直立していて根出草なのがコンニャクとは異なる。
基本的に株毎に性別があり雄花をつけるか雌花をつけるか決まっているが、芋のサイズに応じて性転換する特徴がある。
ほとんどのサトイモ科植物はシュウ酸カルシウム由来の致命的ではない毒を持っているがこの属は特に毒性が強調されることが多い。毒が強いのもあると思うが実が赤くなり非常に美味しそうに見えるのが原因だと思う。
テンナンショウは日本中の湿った森の地表から河川敷まで生息する。地下に芋を作る。

|Pinellia属
|ハンゲ
カラスビシャク
|Arisaema属に似ているが花は雌雄同株なところと偽茎を作らないところなどが違う。
花の観賞価値が高く園芸で人気がある。Arisaema属に比べると花が細く涼し気な印象。
一部の種ではムカゴ(bulbil)と呼ばれる芋を葉柄の上に生成する珍しい特徴を持つ。
名前が似ているハンゲショウはドクダミ科なので注意。

|===

=== Arisareae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Arisarum属
|アリサルム
|見た目はニオイハンゲなどに似ている。
Arisarum proboscideumは花をきのこに擬態していると言われきのこに卵を生むブヨを引き付ける。

|===

=== Arophyteae族 - Aroideae亜科(サトイモ亜科)

マダガスカルに固有の族。乾季に休眠する特徴がある。
素人には調べてもあまり情報が見つからない。

[%autowidth]
|===
|属|一般名|概要

|Arophyton属
|
|マダガスカルに分布し乾季には休眠する。いくつかの種類は芋を作る。
調べてもあまり情報が見つからない。

|Carlephyton属
|
|石灰岩または玄武岩の熱帯落葉樹林、または岩の隙間で成長することが知られている。

|Colletogyne属
|
|調べてもあまり情報が見つからない。

|===

=== Caladieae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|*Caladium属*
|カラジューム
カラジウム
ハイモ
ニシキイモ
|葉がカラフルで独特の模様があるため観賞価値が高く人気がある。アメリカを中心に品種改良が進んでいる。
同じCaladieae族で葉が似てるシンゴニウムと勘違いされやすい。ただシンゴニウムに比べるとカラジウムを育てのは手間がかかる。
南アメリカ大陸原産で森林の開けた場所や川岸に生息する。乾季には休眠する。
芋が腐りやすい場合があるので植える前に薬剤を塗布したほうが良い。

|Jasarum属
|
|カラジウムが水辺で生活してるうちに進化して水中生活に適応した属。葉は長細く流れのある場所を好む。見た目がカラジウムと違いすぎるため分類には苦労したらしい。
ベネズエラに生息し南アメリカ出身のサトイモ科植物の中では唯一水中生活をする。
栽培は難しく酸性土壌と硬度が非常に低い軟水を必要とする。

|Chlorospatha属
|
|Xanthosoma属に近縁でChlorospatha longipodaはChlorospatha属とXanthosoma属の中間の形質を示す。
熱帯アメリカに生息し湿気の多い林床、日陰になった沼地や小川などに生息する。
栽培が難しいことが知られている。

|Hapaline属
|
|東南アジアに生息し湿気の多い林床か石灰岩または玄武岩のくぼみに住む。

|Scaphispatha属
|
|季節的に水没するような地域に生息する。

|*Syngonium属*
|シンゴニウム
シンゴニューム
|葉が美しい観葉植物として人気がある。成長が早くとても育てやすい。葉が似てるカラジュームと勘違いされやすい。
Caladieae族では珍しく芋を作らず匍匐したり登はんする半着生植物(半着生は原始的なサトイモ科では多いが逆にAroideae亜科の中だと4つ程度の属しか知られていない)。木の幹の根本を探すため地上を匍匐中は、暗いところを目指す傾向があるる。根本を見つけると木の幹を登はんして光の方向に成長する。
成長速度が早いので一部熱帯地域では外来種となり厄介な雑草化している。

|*Xanthosoma属*
|アメリカサトイモ
ココヤム
キサントソマ
キサントソーマ
|日本ではほとんど馴染みがないものの南北アメリカ大陸とアフリカでは食用のサトイモとして多く生産されている。食用のサトイモで一番生産されているColocasiaと比べると乾燥に強いので乾燥する地域で好まれる。
Xanthosomaの名前で売られる紛らわしい種類がCaladium属にいる(Caladium lindeniiという種で過去にXanthosomaに分類されていた)。

|===

=== Calleae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Calla属
|ヒメカイウ
|園芸で有名なカラーはZantedeschia属。属名がまぎらわしい。
姿はカラーに似ていて、住処も湿地を好む。
日本だと東北から北海道と寒い地域に生息している。

|===

=== Callopsideae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Callopsis属
|
|
地下で茎を横に伸ばすサトイモ科では珍しい育ち方をする植物。葉はモンステラジェイドのような葉脈に暗い色が落ちて見ごたえがある。小くて地味だが白い花を咲かせる。
タンザニアやケニアに分布し高度800m程度の落ち葉のある林床に生息する。
分類上の位置づけが難しい属だがUlearumと近縁である可能性が示唆されている。
それなりに乾燥に強い。
//QUOTE Ulearumまわり [AROIDS: Plants of the Arum Family]

|===

=== Colocasieae族 - Aroideae亜科(サトイモ亜科)

サトイモ科植物の花の先頭につくことが多い付属体がない。
//TODO 付属体周りの記述が突然出てる

[%autowidth]
|===
|属|一般名|概要

|Alocasia属
|クワズイモ
アロカシア
|クワズイモ(Alocasia odora)は幹立ちしやすく見ごたえのある見た目から中大型のインテリアとして人気が高い。この属の他の種も様々な色や見た目の種がいるので観葉植物として人気がある。
食用で非常に重要なColocasia属と似ているがこちらは芋を食べることが困難なためクワズイモと呼ばれている。見た目だけでなくColocasia属とAlocasia属は非常に近縁な属らしい。
種子がハクビシン
湿潤な低地の森林に生息する。
//TODO 記事が未完成

|Ariopsis属
|
|熱帯雨林に生息する。
切り立った場所に着生している写真が多い。
丸くてソフトな色の葉を持つ。
一度見てみたい。

|Colocasia属
|サトイモ
タロイモ
タロ
コロカシア
|食用として広く普及している属。重要な農作物のためサトイモ科植物の中でも情報がとても多い。
葉が美しく観葉植物としてもそれなりの品種がいる。ただ多くの種類は耐寒性がなく日本の冬は葉を枯らして休眠する事が多い。はっきりしないが原産は熱帯アジアと言われる。
小芋を作って増えるのが基本だが一部ランナーで増える種類がいる。
葉の裏面の葉脈も非常に見応えがあると思う。

|Leucocasia属
|
|Colocasia gigantiaと呼ばれるもの

|Remusatia属
|
|Colocasiaに非常に似ている。ランナーで増える特徴があるが普通のランナーであればColocasiaにも少数ランナーで増える種がいる。ただRemusatiaのランナーは場合によってむかご的に多数の球根を発生させる場合があり特徴的な性質になっている。
むかご的に発生した球根は毛で覆われていて鳥や哺乳類にくっつくことができる。この性質がRemusatia属の生息範囲が広い理由だと言われる。
Remusatiaは根茎植物にも関わらず岩や木にくっついて生活している事がある。
育て方は土に植える限りColocasiaとほぼ同じ。気温が下がると葉が枯れる。枯れたら土から球根を取り出してやらないと腐りがち。
着生植物として育ててみたい。

|Steudnera属
|
|レムサティアに近縁。
中国では加工食品が作られていることから栽培が行われている?

|Vietnamocasia属
|
|2017年頃に報告された属。

|===

=== Cryptocoryneae族 - Aroideae亜科(サトイモ亜科)

水辺を好み水中で育つことも可能な種で構成された族。
所属する2つの属は見た目が似ている事もあるが新芽の巻かれ方で見分けることができる。

[%autowidth]
|===
|属|一般名|概要

|Cryptocoryne属
|クリプトコリネ
|アクアリウムの世界では見ごたえのある根出草として人気が高い属。
ラゲナンドラとの比較で新芽が一方向だけに巻かれている特徴がある(サトイモ科では一般的な巻き方)。サトイモ科ではそれなりに見られる性質だが収縮性のある根を作り茎が土に近づきすぎないように調整している。
インド、東南アジア全域、パプアニューギニアの熱帯地域に生息する。主には流れの早くない川や季節的に浸水する林床などに生息するが、湿地であれば様々な環境に進出していて汽水域に生息する種もいる。
育てる場合のphとして弱酸性が勧められることが多いが、半数の種は石灰質の場所にも生息することが確認されている。そのためphは種ごとに検討したほうが良いのかもしれない。
//QUOTE 汽水の箇所 [MIST LOVERS -Rainforest Plants- / KEISUKE HASE p12]
//QUOTE 石灰質の下り [https://en.wikipedia.org/wiki/Cryptocoryne]

|Lagenandra属
|ラゲナンドラ
|バルダリウムやアクアリウム向けでそれなりに流通している属。クリプトコリネとの比較で新芽が主脈を中心に二方向から巻かれている特徴がある。
インド半島に固有の属で主に川の水辺に生息する。あまり川以外の環境には進出しない特徴がある。
水中で生活できるサトイモ科植物の中では葉が強い方で環境を大幅に変えても葉が枯れづらい。常湿でも問題ないため育てやすい。

|===

=== Culcasieae族 - Aroideae亜科(サトイモ亜科)

// (半着生は原始的なサトイモ科に多いが逆にサトイモ亜科の中だと4つ程度の属しか知られていない)

[%autowidth]
|===
|属|一般名|概要

|Cercestis
|セルセステス
レクトフィラム
Rhektophyllum
|半着生植物のツル植物で木の幹に近寄り着生する。
茎を伸ばす過程でカタフィル(葉柄以外で新芽作るときの鞘)だけの謎の芽を生や
大人の時の葉は深い切れ込みが入り複葉になるため見た目が驚くほど変わる。
Cercestis mirabilisは葉の模様が独特で見応えがあるため人気がある。

|Culcasia
|
|半着生植物のつる植物
Cercestisに似る。

|===

=== Homalomeneae族 - Aroideae亜科(サトイモ亜科)

Philodendreae族に近縁

[%autowidth]
|===
|属|一般名|概要

|Adelonema属
|南アメリカ大陸に生息する。
|ホマロメナによく似ていて、葉が人気のあるホマロメナ・ワリシーして流通している種は厳密にはにはAdelonema属でAdelonema wallisiiと呼ぶのが正しい。
ホマロメナの中でも南アメリカに分布するものをAdelonema属に移動する動きがあるらしい。
//TODO もう少しかけそう?

|Furtadoa属
|フルタドア
|ホマロメナによく似ている。
ホマロメナに比べて茎に沿って発根しやすい特徴があるが、ホマロメナもそれなりに茎から発根するので決定的な特徴ではない。
//TODO もう少し書けそう?

|Homalomena属
|ホマロメナ
セントンイモ
|葉が美しく観葉価値が高い種類が多いためブセファンドラに並んでマニアの取引が多い事で有名な属。
小型で湿度を必要とする種類が多いが、アカジクセントンイモのように常湿で大型化する種類もいる。葉脈の凹凸がはっきりと出ることが多い。
南アジアと南アメリカの渓流などに生息する湿地性植物だが、ホマロメナ属は湿地に対して適応するような進化をそこまでしていない事が知られている。湿った所が好きな属で渓流に行き着いたフシがある。
Schismatoglottideae族に似ているため誤って分類されることが多いが近縁ではない。

|===

=== Montrichardieae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Montrichardia属
|mocca-mocca
|熱帯雨林を流れる川岸に群生する抽水植物。
南アメリカ大陸に分布し現地では一般的な植物。木化した幹で高く直立して群生する様はマングローブのような雰囲気がある。淡水、汽水、海水沿いの湿地で生育する。
サトイモ科植物では珍しく裏表で組織差が少ない葉を作る(他ではAnthurium属の一部種しか知られていない)。静粛すると垂直に葉を展開するようになるので、裏表で同様に光合成をするためだと思われる。
普遍種だが低温に弱く、寿命が短く、非常に大きくなるためか現地以外ではあまり栽培されないらしい。
一度見てみたい。
//QUOTE 裏表の件 [Genera of Aroid]

|===

=== Nephthytideae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Anchomanes属
|
|地下に芋を作る球根植物。幼葉のときは矢じり状の葉を展開する。成熟するとコンニャクのような葉柄を持った三枚程度の複葉を展開する。もっと成熟すると複雑でサトイモ科でもあまり見られない形の複葉を展開する。
葉柄には棘が作られる。
熱帯アフリカの低湿地に生息する。Anchomanes difformisは現地では畑の脇などに生えていて雑草扱い。
//QUOTE 畑の脇の雑草 [https://www.jircas.go.jp/ja/database/ghana/anchomanes_difformis]
//QUOTE 葉の写真 [https://www.gbif.org/species/2870398]

|Nephthytis属
|
|サトイモ科では珍しく地下を横向きに匍匐する根茎植物。矢じり状のだが横幅のほうが広い変わった見た目の葉をつける。
過去に一部のシンゴニウム属の種がNephthytis属と勘違いされていたため検索するとこちらがヒットする場合が多く紛らわしい。
熱帯西部および中央アフリカに生息し湿気の多い森の地面などに生息する。
成長点が地上に出ていると下向きに芽を伸ばして地下に潜ろうとする

|Pseudohydrosme属
|
|分子的な分析の結果Anchomanes属との違いが少なく吸収される可能性が高い。

|===

=== Peltandreae族 - Aroideae亜科(サトイモ亜科)

PeltandraとTyphonodorumは似ているが生息地が地理的に遠い。そのためかつてアフリカ大陸に2つの属を結びつける絶滅した属があったと予想されている。

[%autowidth]
|===
|属|一般名|概要

|Peltandra属
|ペルタンドラ
arrow arum
|主に湿地に住む抽水植物で地中に芋を形成する。湿地のサトイモ科では一般的だが芋は低酸素に耐性枷ある。小芋を増やして群生するが繁殖は主に種子で行う。果実は水に落ちると果実のコーティングが膨張して破裂するようになっている。破裂せずに種子から果肉が取れない場合発芽率が下がる。
観葉植物としてはあまり人気がないがアメリカの普遍的な固有種のため英語圏での情報が厚い。
//QUOTE [https://edis.ifas.ufl.edu/publication/AG400]

|*Typhonodorum属*
|ティフォノドルム
|唯一の種のTyphonodorum lindleyanumは大型化し見ごたえがあることから熱帯植物園では定番。
成長すると葉が大きくなり幹も太くなる。幹は木もしくはクワズイモの芋のように見えるがこれは葉柄が集まったできた偽茎でバナナの木などに近い。
マダガスカルとその近郊のアフリカ大陸に分布し、沼地や潟(汽水)などのの湿地に住む抽水植物。

|===

=== Philodendreae族 - Aroideae亜科(サトイモ亜科)

フィロデンドロンという名前で流通する種が所属する族。セロームやクッパカズラなどの幹が木化する種は基本的にThaumatophyllum属。Homalomeneae族に近縁。
一部の種はパイナップルやマンゴーに風味が似た甘い果実をつける。

[%autowidth]
|===
|属|一般名|概要

|Philodendron属
|フィロデンドロン
|(半着生は原始的なサトイモ科に多いが逆にサトイモ亜科の中だと4つ程度の属しか知られていない)
//TODO 未完成

|Thaumatophyllum属
|Meconostigma
|

|===

=== Philonotieae族 - Aroideae亜科(サトイモ亜科)

過去にSchismatoglottis族に分類されていたが、分子的な分析の結果でSchismatoglottis族ではない事が判明した種で構成された族。
Schismatoglottis族よりはCryptocoryneae族に近縁。

[%autowidth]
|===
|属|一般名|概要

|Philonotion属
|
|南アメリカに生息する。

|===

=== Pistieae族 - Aroideae亜科(サトイモ亜科)

Colocasieae族と近縁。

[%autowidth]
|===
|属|一般名|概要

|Englerarum属
|
|情報が少なすぎてあまりわからない。
唯一の種のEnglerarum Nauheimerはクワズイモに似ている。

|Pistia属
|ボタンウキクサ
ウォーターレタス
ウォーターキャベツ
|非常に特殊な形態を持つ属で水面を浮遊生活をする。同じく浮遊生活を行うウキクサ亜科とは近縁ではなく後の時代に独自に進化してこのような形態を獲得した。
分子的な研究から近縁の属が知られているが底との比較で体の形態が様変わりしている部分が多い。ウキクサ亜科との比較で水面生活は体の形態を変化させる強い圧力を持っていると考えられている。
//比較的流れがある所でも場所を維持できるようになっている(ウキクサ亜科は流れに弱い)。ランナーで増殖する。
非常に増殖能力が高いため強力な侵略種として知られる。日本ではよく売られていた水草だったが特定外来生物に指定されたため通常は飼育することができなくなった。暑さには強いが寒さには弱く本州では一部地域をを除いてあまり定着していない。
侵略種として広い地域に生息するため原産地について諸説があるが化石による分析では北アメリカ大陸のフロリダが有力。現在もフロリダにはボタンウキクサが生息するが過去に一度絶滅していて、現在の生息しているものは後の時代に外部から侵入して再度定着したものだと考えられている。
//QUOTE 水面生活は体の形態 [Cobbania属周りの論文にそんな事が書いてあったはず]


|Protarum属
|
|セイシェル固有。
Colocasieae族に分類されている場合がある。

|===

=== Schismatoglottideae族 - Aroideae亜科(サトイモ亜科)

Schismatoglottisに近縁な種で構成されている族で、構成されるほとんどの属がSchismatoglottis属の進化の過程で種分化して生まれたものだと予想されている。Schismatoglottis属は種分化が非常に激しい特徴を持つためためSchismatoglottideae族全体で非常に多種多様で大幅に異なった形態を持った種が存在する。族間の比較ではCryptocorynae族に近縁。

Schismatoglottideae族と生息地が被るホマロメナ属も非常に種分化しやすく様々な種類がいる。遠縁な属なもののSchismatoglottideae族に非常によく似る種がいるため見分けるのが難しい。ただ大抵のSchismatoglottideae族は葉柄鞘が短いか作らずホマロメナ属は葉柄鞘が長い特徴がある。確実に見分けるには花を使うことが多い。
//QUOTE この下りは独自調査のため怪しい

Schismatoglottideae族では形態的な特徴から色々な属が定義されてきたが、分子的な分析の結果として現状の分類はかなり混乱している事が分かり始めている。中にはあまり意味をなしてい可能性がある属もありSchismatoglottideae族全体で大幅に整理が進んでいる。

[NOTE]
下記の属は調べてもよくわからなかったので省略。
Apoballis属、Galantharum属、Gamogyne属、Gosong属、Hera属、Heteroaridarum属、Hottarum属、Kiewia属、Nabalu属、Naiadia属、Ooia属、Phymatarum属、Pichinia属、Pursegloveia属、Rhynchopyle属、Schottarum属、Tawaia属、Toga属、Vesta属、Schottariella属

//QUOTE Tawaia [https://araceae.atlassian.net/wiki/spaces/AROID/pages/edit-v2/4784129]

[%autowidth]
|===
|属|一般名|概要

|Aridarum属
|アリダルム
|分子的な分析でSchismatoglottisとの違いが曖昧になった属。

|Bakoa属
|
|分子的な分析でSchismatoglottisとの違いが曖昧になった属。

|Bakoaella属
|
|2018年にSchismatoglottis属から独立した。
流れの早いところに住む

|*Bucephalandra属*
|ブセファンドラ
|アクアリウムで見応えのある水草として人気がある。非常に種類が多いためマニアの取引が多い事で有名。
殆どの種がボルネオ島原産で、渓流の中や付近で岩などに着生する匍匐性の植物。
仏炎苞の上部は開花時期に取れることが多い。上部が取れた仏炎苞はカップ状で水滴が入った時に勢いよく水が跳ねる。この性質を利用してカップ内にできた種を拡散すると言われる。

|Piptospatha属
|ピプトスパサ
|分子的な分析でSchismatoglottisとの違いが曖昧になった属。

|Schismatoglottis属
|スキスマトグロッティス
|limbが取れる特徴
三分の一の種がSchismatoglottis calyptrataに近縁。
柵状組織の細胞がランダムに並び版を作る。
熱帯雨林か元熱帯雨林の地域に住む。
季節性の高い地域では生息できない。
通常のサトイモ科植物のように花が咲いた後に頂点に新しい枝を作る種と、花が咲いた後枝の低い位置から側芽を出して成長し直す種がいる(Schismatoglottis calyptrataに近縁)。
葉から芽が出る?

|===

=== Stylochaetoneae族 - Aroideae亜科(サトイモ亜科)

分子的な研究ではZamioculcadoideae亜科に近縁な可能性が示唆されている。

[%autowidth]
|===
|属|一般名|概要

|Stylochaeton属
|
|主にアフリカ大陸に生息する。

|===

=== Spathicarpeae族 - Aroideae亜科(サトイモ亜科)

主に南アメリカ大陸に分布する種で構成されている。
Dieffenbachieae族はこちらに吸収された。
連続したリングまたは別個の硬膜組織が発達する可能性があります (Engler 1920b)。樹脂および粘液管および空洞、ラチシファー、およびさまざまな異形細胞を含む、多種多様な分泌組織が存在します。これらの構造の多くは、植物の他の部分でも発生し、後で説明します

[%autowidth]
|===
|属|一般名|概要

|Asterostigma属
|
|熱帯、亜熱帯の南アメリカに分布。湿気の多い森林。地生植物、林床。季節的に休眠を行う。芋を作る。
星型の柱頭

|Bognera属
|
|

|Croatiella属
|
|

|Dieffenbachia属
|ディフェンバキア
シロガスリソウ
|葉に見応えがあり暗い室内での飼育に向いていることから観葉植物として人気がある。
熱帯アメリカに生息する。
Dieffenbachia属はAglaonema属と似ているいる要素が多いので見間違われやすいが近縁ではない。分かりやすい見分け方は主脈に対して葉脈が10以下ならAglaonema属。20程度ならDieffenbachia属の可能性が高い

|Gearum属
|
|種はGearum brasilienseのみの芋を作る球根植物。見た目がコンニャクに似ている(Spathicarpeae族ではこのタイプの葉は珍しい？)。
ブラジルの季節性が強く水没する時期もあるようなサバンナに生息する。
情報があまり見当たらない。

|Gorgonidium属
|
|標高900-3000mの

|Incarum属
|
|

|Lorenzia属
|
|

|Mangonia属
|
|季節的に水没する地域に生息する。

|Spathantheum属
|
|Spathicarpaに近縁。分かりづらいが仏炎苞と花が癒合している。花の見た目はコーンぽい。芋を作る。
アンデス山脈に固有で岩石土壌の草原に生息する。

|Spathicarpa属
|スパティカルパ
|花と仏炎苞が結合してしまっているとにかく珍しい形態のサトイモ科植物。
葉はサトイモ科にしては柔らかい葉をロゼット状に展開する。仏炎苞の中央に仏炎苞と融合した花が並ぶ。芋を作る。
南アメリカに生息し季節的に水没する林縁や石灰岩の土壌ポケットなどに生息する。
Spathantheum属に近縁だと考えられている。

|Synandrospadix属
|
|唯一の種のSynandrospadix vermitoxicusは2kgにもなる大きな芋を作る特徴がある。
南アメリカ中部の乾燥した丘の斜面や道路脇に生息する普遍種。

|Taccarum属
|タッカルム
|雄花が非常に伸びる

|===

=== Thomsonieae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Amorphophallus属
|コンニャク
アモルフォファルス
|主に和食で食材として使われるコンニャクを作るために、日本で栽培されている事が有名。他に世界一大きな花を咲かせる植物としてショクダイオオコンニャク(Amorphophallus titanum)は名前がよく知られている。
基本的に芋に付き年に一枚しか葉を展開しない特徴がある。一枚の葉が裂けて複葉を展開するので見た目は葉を複数展開しているように見えるがこれは一枚の葉。ちなみに花を咲かせる年は葉を展開しない。他に茎に白い斑点を持つ特徴があり、これは地衣類を模倣していて地衣類が足につくことを嫌う哺乳類を避けようとしていると考えられている。一部の種では葉柄や葉の上にムカゴ(bulbil)と呼ばれる芋を形成する珍しい特徴を持つ。
芋を作るサトイモ科植物は多いが主にColocasia型とAmorphophallus型の2つに分けられると考えられている。Amorphophallus型は小芋を作った後に親芋から分離しようとせず親芋の成長に伴って小芋にも栄養が行き一緒に成長する。ちなみにAmorphophallus属の小芋は長細い。
食用としての栽培では芋を大きくしていく必要があるため食べれるまで数年がかりになる。

|===

=== Zantedeschieae族 - Aroideae亜科(サトイモ亜科)

[%autowidth]
|===
|属|一般名|概要

|Zantedeschia
|オランダカイウ
カラー
サンテデスキア
|花が大変美しいため切り花や観葉植物として人気がある。主にアメリカとニュージーランドで品種改良が行われている。
アフリカ南部原産で湿地帯に広く生息する。世界中で移入して野生化している。
収縮性のある根を持ち

|===

=== Zomicarpeae族 - Aroideae亜科(サトイモ亜科)

主に南アメリカ大陸に生息する。
全体的に情報が少ないくて謎が多い族。

[%autowidth]
|===
|属|一般名|概要

|Filarum属
|
|唯一の種のFilearum manserichenseは雄しべの形態が特殊でかっこいい花を咲かせる。
アマゾン川流域やペルーに生息する。

|Ulearum属
|ウレアルム
|地下で茎を横に伸ばすサトイモ科では珍しい育ち方をする属。
// カンアオイのような葉や見た目。
南アメリカ大陸の林床などに生息する。
体の形態的な特徴からCallopsisと近縁である可能性が示唆されている。ただCallopsisはアフリカ大陸に生息するためUlearumとの地理的な隔離が激しい。Ulearumも分布が散発的な種がいるため、これらは遺存種的な状況なのかもしれない。
それなりに乾燥に強く、ゆっくり成長する。

|Zomicarpa属
|
|地下に芋を作る。葉の生え方がテンナンショウ(Arisaema属)に似る。
ブラジル北東部に生息する。
情報が少ない。

|Zomicarpella属
|
|アマゾン川流域に生息する。
情報が少ない。

|===
