:hardbreaks:
:toc:
:toc-title: 目次
:page-pariority-key: 2

= サトイモ科植物一覧

幅広いサトイモ科植物を見てみたいと思い初心者が属単位で片っ端から調べて見ました。
園芸、農業、アクアリウムの世界で有名な属は黄色で網掛けしました。
内容は適当な事を書いている場合があるかもしれません。

== Gymnostachydoideae亜科(ギムノスタキス亜科)

サトイモ科の中では最古に分化した亜科。

[%autowidth]
|===
|属|一般名|概要

|Gymnostachys属
|ジムノスタキス
|サトイモ科植物の中では異様な見た目をしていて外見はショウブ科植物によく似ている。
葉はショウブのように葉柄を持たず細長い。花はサトイモ科植物らしく仏炎苞を持つ。サトイモ科とショウブ科は近縁なためサトイモ科で古くに分化したGymnostachys属は2つの科の中間的な性質を持っているのだと思われる。
オーストラリアに生息し湿ったユーカリの森に生息する。
サトイモ科の中では非常に興味深い属だが園芸の世界ではほとんど見かける事がない。筑波実験植物園に展示されていることがある。
|===

== Orontioideae亜科(水芭蕉亜科)

ギムノスタキス亜科と姉妹亜科。水辺を好む種が多い。
サトイモ科ではそれなりに見られる性質だが、どの種も収縮性のある根を持っていてこの根を収縮させることで茎の位置などを調整する。
サトイモ科では花を咲かせると一度枝(シュート)が終了して頂点から再び新しい枝が分岐して成長を再開する事が多いが、Orontioideae亜科では花を咲かせた後の新しい枝が二枚下の葉の下と普通より低い位置から始まる特徴がある。

[%autowidth]
|===
|属|一般名|概要


|*Lysichiton属*
|ミズバショウ
スカンクキャベツ
|寒い地域の湿地に住み、大きな花を咲かせるサトイモ科植物。花が咲いた時と葉を切った時にひどい悪臭がするらしい。
東アジアからアメリカ大陸まで生息し、日本だと北海道から日本海沿岸にミズバショウが分布する。
暑さに弱いため通年飼育の難易度が高い。

|*Symplocarpus属*
|ザゼンソウ
|寒い地域の湿地に住み、大きな花を咲かせ、悪臭があるなどLysichitonに似るがSymplocarpus属では太くて収縮性のある根を持つ特徴がある。
東アジアからアメリカ大陸まで生息し、日本だと北海道から日本海沿岸に分布する。
暑さに弱いため通年飼育の難易度が高い。

|Orontium属
|オロンティウム
オロンチウム
golden club
|水辺に住む抽水植物。水芭蕉亜科の中では珍しく温かい所でも育つ。
仏炎苞が見当たらないサトイモ科でも珍しいタイプの花を咲かせる(花の下の方にある仏炎苞らしきものは仏炎苞とは違うとか)。
他の水芭蕉亜科の種と違いそこまで臭くない。が睡蓮などのように自身の腐った葉などで周りの土壌を作っていくタイプの植物のため成長するに連れてだんだん臭くなってくる。
稀だが公園の池に植えられたり、水中生活もできるのでアクアリウムで水草として使われることがある。

|===