:hardbreaks:
:toc-title: 目次

= 食用のサトイモ科植物

サトイモ科植物は非常に種数が多い科だが食べるとものすごい痛みを引き起こすシュウ酸カルシウムの問題があり、食用にできる種は多くない。ただ、色々調べていくと変わった種類が食べられている場合がある。
このページでは、現代、過去に文化的に食用にされたことのあるサトイモ科植物についての情報についてまとめている。

情報があまりないので詳しい人がいたら教えてほしいです。

[%autowidth]
|===
|学名|一般名|概要

|Arisaema serratum
|マムシグサ
|実や芋が充実していることから食べれそうに見えるが、強力なシュウ酸カルシウムを持っているため食べると非常に痛い目を見る植物として知られている。
そこら中に生えていることと、うまく調理すると味がジャガイモのようで美味しいため、工夫して昔は食べられていた。

特に北海道のアイヌが冬の食料として食べていた話が有名で、成熟した芋を加熱してシュウ酸カルシウムの多い芯を取り除くことで食べられていた。
本州では、芋をすりおろしたものを水にさらしてシュウ酸カルシウムを抜いたものを練って団子にして食べていたらしい。

基本的には食用で栽培が行われることはない。
非常に近縁種が多いため、マムシグサ以外にもArisaema属の色々な種が食べられていたと思われる。

//下記のブログが参考文献も書いてあって非常に詳しかったです。
//https://www.yamareco.com/modules/diary/990-detail-20396

//QUOTE ジャガイモのような味 [https://www.youtube.com/watch?v=32d2C02U7Q4]
//QUOTE アイヌの話 [https://ainugo.nam.go.jp/siror/book/detail_sp.php?page=book&book_id=P0363]
//QUOTE 食べ方 [https://www.yamareco.com/modules/diary/990-detail-20396]
//MEMO アイヌの食べ方 [私の草木漫筆]
//MEMO 本州での調理法 [食べられる野草と料理法 福島誠一、１９９８年]
//MEMO 調理法が乗っているとか [毒草の科学 一戸良行、１９８０年]
//MEMO 伝統的な食べ方 [分類アイヌ語辞典第一巻植物篇 知里眞志保著、日本常民文化研究所彙報、1953年]

|Alocasia macrorrhizos
|インドクワズイモ
|クワズイモ(Alocasia odora)と同様に芋が充実しているがシュウ酸カルシウムが強くて食えない種としてさまざまな地域で知られている。
ただ、東南アジアやオーストラリアではエグ味の少ない品種を長時間調理することで食用にする方法が知られていて栽培されれている。
主に、葉柄や芋を食用にする。

食用として日本でも栽培されているハスイモは非常に古い時代にインドクワズイモとColocasia esculentaを人為的に交配することで作られた品種だと考えられている。

|Alocasia brancifoli
|
|
//QUOTE 食べられてないかも [タロイモは語る p98]

|*Amorphophallus konjac*
|コンニャク
|原産地はインドからインドシナ半島で日本には中国経由で調理方法とともに渡ってきた。
主に芋を食用とするが、他のサトイモ科植物と同様にシュウ酸カルシウムが含まれているため複雑な加工を行うことが知られている。
食材のこんにゃくを作るために日本や中国では栽培がおこなわれている。

加工済みのコンニャクはぷにぷにしているがこれはAmorphophallus konjacに含まれるコンニャクマンナンが影響している。

|Amorphophallus paeoniifolius
|ゾウコンニャク
|コンニャクの近縁種だが日本ではあまり食べられる事はない。東南アジア、オセアニア、マダガスカル、インド、スリランカなどでは食用にされている。
シュウ酸カルシウムが含まれるため潰してよく煮てから食べられる。インドやスリランカではシュウ酸カルシウムの少ない品種が存在しカレーの材料にされたりする。

コンニャクマンナンが含まれていないので、いわゆる食材のコンニャクをゾウコンニャクから作ることはできない。
//QUOTE http://kampong.life.coocan.jp/Nov05/Part3/contents/elephantyam.html

|Calla palustris
|ヒメカイウ
|寒冷地に適応しているサトイモ科植物で大きめの芋を作る。
スカンジナビアでは根を煮てすりつぶし、しばらく置くことで毒抜きをしてから食用にすることがあったらしい。
日本、ロシアでも食べられていた可能性が示唆されている（多分救荒食）。
//QUOTE スカンジビアナ [https://ja.wikipedia.org/wiki/%E3%83%92%E3%83%A1%E3%82%AB%E3%82%A4%E3%82%A6]
//QUOTE 日本ロシア [タロイモは語る]

|*Colocasia esculenta*
|里芋
|世界で一番栽培されているサトイモ科植物。いわゆるスーパーでよく見かける里芋。
アフリカ大陸、オセアニア、アジア、アメリカ大陸などで栽培が行われ食用にされている。

東南アジア原産でコメ栽培伝来以前に日本に渡ってきた芋系の栽培植物の一つ。
日本列島など寒い地域では花を咲かせることができず小芋などを使って株分けして栽培するため、長い栽培の歴史の割には品種はそこまで多くなく、石川早生を除く日本で食べられるほとんどの品種で中国や東南アジアに近縁の品種が存在する。

主に芋を煮て食用にすることが多いが、葉柄を食用にしたり（ずいき）、日光に当てず育てたもやしのような芽（芽芋）を食べたりする事もある。
海外ではやわらかい匍匐枝を食用にすることも多い。

日本では保存性に優れるジャガイモに押され気味で生産量が減少傾向。
//QUOTE コメ以前 [タロイモは語る][海を渡ったタロイモ]
//QUOTE 石川早生を除くと中国にルーツがある [サトイモ: 栽培から貯蔵、種芋生産まで (新特産シリーズ)]
//QUOTE 生産量が落ちている [サトイモ: 栽培から貯蔵、種芋生産まで (新特産シリーズ)]
//QUOTE 匍匐枝　[http://test-minpaku.com/museum/enews/234]

|Colocasia antiquorum
|ヤマサトイモ
|

|*Colocasia gigantia*
|ハスイモ
りゅうきゅう
|非常に大きくなるサトイモ科植物だが芋は小さい。主に葉柄（芋茎）を食用にするために栽培される。
日本では九州や四国の方で現在も栽培が行われている。

ハスイモは、非常に古い時代にインドクワズイモ（Alocasia macrorrhizos）とColocasia esculentaとの人為的な交配によって作られた品種だと考えられている。

|Cyrtosperma senegalensis
Cyrtosperma merkusii
|キルトスペルマ
ミズズイキ
ヌマサトイモ
|主に芋を食べるために栽培される。
古くから東南アジアで栽培されいた芋系植物の中の一つ。キルトスペルマは栽培に手間がかかることと、芋にシュウ酸カルシウムが含むため、現在でも栽培している地域は少ない。
ただ、ツバル、キリバスといった珊瑚礁で作られた島では、Cyrtospermaが栽培する事が可能な数少ない食物のため主要な農作物になっていた。

Cyrtospermaの中でどの種が食用にされているのか未調査。
//QUOTE Cyrtosperma senegalensis [タロイモは語る p20]

|Eminium spiculatum
|
|中東を中心とした乾燥した地域に生えるArum属に近縁なEminium属の種。
主に種や芋を食用にし、エジプトの遊牧民などは根茎をジャガイモのように茹でて食べる。
//QUOTE [https://en.wikipedia.org/wiki/Eminium_spiculatum]

|Montrichardia arborescens
|yautia madera
moco-moco
|ブラジルなど南アメリカ大陸熱帯域の河川の広い範囲でマングローブを作っている植物。
バナナやパイナップルを思わせるような大きな果実をつける。そのその果肉やタネを食べる事ができる。

現地では簡易な栽培が行われる事が多く主食だったらしい。

|Typhonodorum lindyanum
|ティフォノドルム
|ティフォノドルムはセイシェル諸島やマダガスカルに生えていて、現地では救荒植物として食べられてきた。
主に根茎や種子を食べる。

ティフォノドルムの太い茎は根茎ではなく、実際には葉柄などでできた偽茎というものなので野菜的な感じだろうか。あまり美味しそうな植物には見えない。
情報が少なくどれくらい食べられていたのか謎。
//QUOTE [タロイモは語る p120]

|Orontium aquatum
|
|北アメリカで根と種子を食用にしていた。


|Peltandra virginica
|
|アメリカのタッカッホーという地域では、インディアンの主食野菜になっていた。
//QUOTE https://www.eattheweeds.com/peltandra-virginica-starch-storer-2/

|Philodendron
|フィロデンドロン
|実が食べれる。

|Pistia stratiotes
|ウォーターレタス
|
//QUOTE https://en.wikipedia.org/wiki/Pistia
//QUOTE https://yamashina-botanical.com/botanical/%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%A6%E3%82%AD%E3%82%AF%E3%82%B5/

|Schismatoglottis megaphylla
|スキスマトグロッティス
|地上茎はえぐ味がすくないので食べることができる。
台湾ではの蘭島では栽培植物と一緒に分布を広げていることから栽培されて食べられていたとみられるが、現代では食べられていない。

タロイモは語るという本で上記の話を見かけたもののmegaphyllaという種が何者なのか不明。
//QUOTE homalomenaスキスマ [タロイモは語る p68]

|Wolffia globosa
|ミジンコウキクサ
|ミジンコウキクサは0.3–1.5 mm程度の水面に浮かぶ非常に小さい植物で、タイなどでは昔から食べられてきた。
最近では、増殖しやすくタンパク質をはじめとして栄養豊富なため次世代の食品の材料として注目を浴びている。
どちらかというと縮小気味の食用のサトイモ科植物栽培の中では近年利用が拡大し始めているものかもしれない。

|Lasia spinosa
|ミズヤツデ
|インドネシアなど東南アジアの一部地域では葉柄などをよく火にかけて毒抜きすることで野菜として食べる。

Lasia属は葉柄に針がたくさんあるので事前に取る必要があると思う。

|Monstera deliciosa
|モンステラ
|モンステラは時折花を咲かせて大型の実を付ける。その実を食べる事ができる。
タロイモは語るという本によれば、パラグアイでモンステラの実を食べるために栽培を行なっていた農家がいたらしい。
広く食べられていたかは不明。
//QUOTE [タロイモは語る p119]

|*Xanthosoma sagittifolium*
|アメリカサトイモ
ヤバネサトイモ
ムラサキヤバネイモ
|世界で二番目に食用栽培されているサトイモ科植物。
Colocasia esculentaに比べて必要な水の量が少ないので乾燥した地域で好まれる。

主に芋を食べるために栽培される。
//MEMO 二番目という明確な情報がない
//QUOTE 生産量の話 [タロイモは語る]

|===

== 食用にされている可能性がありそうな種についてのメモ

ヨーロッパで一般的なArumは薬にされていたことがあるという話があるので、食用にされていた可能性があるかもしれない。
シマクワズイモは人為的に作られた種だと考えられていてさまざまな地域に導入されているので食用にされていたかもしれない。
Steudneraは中国の方で漢方製品が作られているように見えるので食用にされているかもしれない。がColocasiaのシノニムとしてSteudneraという名前が使われているだけかもしれない。
//QUOTE colocasia affinus [タロイモは語る p76]
//QUOTE homalomenaスキスマ [タロイモは語る p68]