:hardbreaks:
:toc-title: 目次

= 食用のサトイモ科植物

サトイモ科といえばスーパーで売っているサトイモ（Colocasia esculenta）が思い浮かびます。
ただ、サトイモ科は3000種もいるにもかかわらず、食べられている種はそれほど多くないです。
（情報があまりないので詳しい人がいたら教えてほしいです）

[%autowidth, cols="1,2,3a"]
|===
|学名|一般名|概要

|Arisaema serratum
|マムシグサ
|日本固有の植物。
日本中に生えていて、実や芋が充実してい美味しそうに見えるが、全体的に強力なシュウ酸カルシウムを持っているため食べれない植物として一般的には知られている。
しかし、昔は一部の人に食べられていた。

北海道のアイヌでは、成熟した芋を加熱してシュウ酸カルシウムの多い芯を取り除くことで食べていた。
本州では、芋をすりおろしたものを水にさらしてシュウ酸カルシウムを抜いたものを練って団子にしたり、囲炉裏の中に長時間埋めて加熱することで食べられていた。

うまく調理すると味がジャガイモのようで美味しいらしい。

観葉植物としては人気があるが、食用目的で栽培が行われることはない。
非常に近縁種が多いため、マムシグサ以外にもArisaema属の色々な種が食べられていたと思われる。

[.inline-quote]
.参考にしたもの
****
下記のブログが参考文献も書いてあって非常に詳しかったです。
https://www.yamareco.com/modules/diary/990-detail-20396

ジャガイモのような味
https://www.youtube.com/watch?v=32d2C02U7Q4

アイヌの話
https://ainugo.nam.go.jp/siror/book/detail_sp.php?page=book&book_id=P0363

本州での食べ方
https://www.yamareco.com/modules/diary/990-detail-20396

他、読んでないけど関連ありそうな文献
アイヌの食べ方 [私の草木漫筆]
本州での調理法 [食べられる野草と料理法 福島誠一、１９９８年]
調理法が乗っているとか [毒草の科学 一戸良行、１９８０年]
伝統的な食べ方 [分類アイヌ語辞典第一巻植物篇 知里眞志保著、日本常民文化研究所彙報、1953年]
****

|Alocasia macrorrhizos
|インドクワズイモ
ジャイアントタロ
|オセアニア、東南アジアなどのオーストロネシアで食用として伝統的に栽培されてきたサトイモ科植物のうち一つ。
シュウ酸カルシウムの結晶を多く含むため長時間調理しないと食べれない。
主に芋を食用にする。一般的ではないが葉や茎を食べる場合もある。

日本で栽培されるハスイモ（Colocasia antiquorum）は非常に古い時代にインドクワズイモとColocasia esculentaを人為的に交配することで作られた品種だと考えられている。

[.inline-quote]
.参考にしたもの
****
英語のWikipedia
https://en.wikipedia.org/wiki/Alocasia_macrorrhizos
****

|*Amorphophallus konjac*
|コンニャク
|原産地はインドからインドシナ半島で、日本には中国経由で調理方法とともに渡ってきた。
主に芋を食用とするが、他のサトイモ科植物と同様にシュウ酸カルシウムが含まれているため複雑な加工を行うことが知られている。
食材のこんにゃくを作るために日本や中国では栽培がおこなわれている。

加工済みのコンニャクはぷにぷにしているがこれはAmorphophallus konjacに含まれるコンニャクマンナンが影響している。

[.inline-quote]
.参考にしたもの
****
諸々
群馬県特作技術研究会.コンニャク: 栽培から加工・販売まで (新特産シリーズ).農文協
****

|*Amorphophallus muelleri*
|コンニャク
|もう一つのこんにゃく

|Amorphophallus paeoniifolius
|ゾウコンニャク
|オセアニア、東南アジアなどのオーストロネシアで伝統的に栽培されてきたサトイモ科植物のうち一つ。
コンニャクの近縁種だが日本ではあまり食べられる事はない。東南アジア、オセアニア、マダガスカル、インド、スリランカなどでは食用にされている。
シュウ酸カルシウムが含まれるため潰してよく煮てから食べられる。
インドやスリランカではシュウ酸カルシウムの少ない品種が存在しカレーの材料にされたりする。

コンニャクマンナンが含まれていないので、ゾウコンニャクから食材のコンニャク作ることはできない。

[.inline-quote]
.参考にしたもの
****
ゾウコンニャクでこんにゃくが作れない件
http://kampong.life.coocan.jp/Nov05/Part3/contents/elephantyam.html
****

|Calla palustris
|ヒメカイウ
|寒冷地に適応しているサトイモ科植物で大きめの芋を作る。
スカンジナビアでは根を煮てすりつぶし、しばらく置くことで毒抜きをしてから食用にすることがあったらしい。
日本、ロシアでも食べられていた可能性が示唆されている（多分救荒食）。

[.inline-quote]
.参考にしたもの
****
スカンジビアナで食用にする件はwikipediaから。（引用元の本が高騰している…）
https://ja.wikipedia.org/wiki/%E3%83%92%E3%83%A1%E3%82%AB%E3%82%A4%E3%82%A6

日本やロシアで食用にされる件
小西達夫.タロイモは語る.東京農大出版会
****

|*Colocasia esculenta*
|里芋
タロ
タロイモ
|世界で一番栽培されているサトイモ科植物。いわゆるスーパーでよく見かける里芋。
東南アジア原産で、オセアニア、東南アジアなどのオーストロネシアで伝統的に栽培されてきたサトイモ科植物のうち一つで、徐々に北上して米伝来以前の日本にやってきた。
日本列島など寒い地域では花を咲かせることができず小芋などを使って株分けして栽培するため、長い栽培の歴史の割には品種はそこまで多くなく、石川早生を除く日本で食べられるほとんどの品種で中国や東南アジアに近縁の品種が存在する。

アフリカ大陸、オセアニア、アジア、アメリカ大陸などで栽培が行われ食用にされている。

主に芋を煮て食用にすることが多いが、葉柄を食用にしたり（ずいき）、日光に当てず育てたもやしのような芽（芽芋）を食べたりする事もある。
日本ではあまり知られていないものの海外ではやわらかい匍匐枝も人気がある。
（日本では匍匐枝を頻繁に出す品種をあまり育てていないことも要因な気がする）

日本では保存性に優れるジャガイモに押され気味で生産量が減少傾向な気がする。

[.inline-quote]
.参考にしたもの
****
コメ以前
小西達夫.タロイモは語る.東京農大出版会
橋本征治.海を渡ったタロイモ.関西大学出版

石川早生を除くと中国にルーツがある
松本 美枝子.サトイモ: 栽培から貯蔵、種芋生産まで (新特産シリーズ).農文協

生産量が落ちている件
松本 美枝子.サトイモ: 栽培から貯蔵、種芋生産まで (新特産シリーズ).農文協

匍匐枝を食用にする件
http://test-minpaku.com/museum/enews/234
****

|Colocasia antiquorum
|ヤマサトイモ
エビイモ
|中国原産のサトイモ。日本では長細くでエビのように見えるエビイモという品種が知られている。

名前が良く似ているヤマイモ、ヤマノイモと呼ばれる植物は全く別の植物なので注意。

|*Colocasia gigantia*
|ハスイモ
りゅうきゅう
|非常に大きくなるサトイモ科植物だが芋は小さい。主に葉柄（芋茎）を食用にするために栽培される。
日本では九州や四国の方で現在も栽培が行われている。

ハスイモは、非常に古い時代にインドクワズイモ（Alocasia macrorrhizos）とColocasia esculentaとの人為的な交配によって作られた品種だと考えられている。

|Cyrtosperma merkusii
Cyrtosperma senegalensis
|キルトスペルマ
ミズズイキ
ヌマサトイモ
|主に芋を食べるために栽培される。

オセアニア、東南アジアなどのオーストロネシアで伝統的に栽培されてきたサトイモ科植物のうち一つ。

キルトスペルマは栽培に手間がかかることと、芋にシュウ酸カルシウムが含むため、現在栽培している地域は少ない。
ただ、ツバル、キリバスといった珊瑚礁で作られた塩分が多く土壌が特殊な島では、Cyrtospermaが栽培可能な数少ない植物の一つのため主要な農作物になっている。

[.inline-quote]
.参考にしたもの
****
Cyrtosperma senegalensisが栽培されていた件
小西達夫.タロイモは語る.東京農大出版会,p20
****

|Eminium spiculatum
|
|中東を中心とした乾燥した地域に生えるArum属に近縁なEminium属の種。
主に種や芋を食用にし、エジプトの遊牧民などは根茎をジャガイモのように茹でて食べる。

[.inline-quote]
.参考にしたもの
***
英語のwikipediaを参考に作った
https://en.wikipedia.org/wiki/Eminium_spiculatum
***

|Montrichardia arborescens
|yautia madera
moco-moco
|ブラジルなど南アメリカ大陸熱帯域の河川の広い範囲でマングローブを作っている植物。
バナナやパイナップルを思わせるような大きな果実をつける。そのその果肉やタネを食べる事ができる。

現地では簡易な栽培が行われる事が多く主食だったらしい。

|Typhonodorum lindyanum
|ティフォノドルム
|ティフォノドルムはセイシェル諸島やマダガスカルに生えていて、現地では救荒植物として食べられてきた。
主に根茎や種子を食べる。

ティフォノドルムの太い茎は根茎ではなく、実際には葉柄などでできた偽茎というものなので野菜的な感じだろうか。あまり美味しそうな植物には見えない。
情報が少なくどれくらい食べられていたのか謎。

[.inline-quote]
.参考にしたもの
****
小西達夫.タロイモは語る.東京農大出版会,p120
****

|Orontium aquatum
|
|北アメリカでは根と種子を食用にしていた。


|Peltandra virginica
|
|アメリカのタッカッホーという地域では、インディアンの主食野菜になっていた。

[.inline-quote]
.参考にしたもの
****
https://www.eattheweeds.com/peltandra-virginica-starch-storer-2/
****

|Philodendron
|フィロデンドロン
|実が食べれる。

|Pistia stratiotes
|ウォーターレタス
|食べるらしい

[.inline-quote]
.参考にしたもの
****
https://en.wikipedia.org/wiki/Pistia
https://yamashina-botanical.com/botanical/%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%A6%E3%82%AD%E3%82%AF%E3%82%B5/
****

|Schismatoglottis megaphylla
|スキスマトグロッティス
|地上茎はえぐ味がすくないので食べることができる。
台湾ではの蘭島では栽培植物と一緒に分布を広げていることから栽培されて食べられていたとみられるが、現代では食べられていない。

タロイモは語るという本で上記の話を見かけたもののmegaphyllaという種が何者なのか不明。

[.inline-quote]
.関連情報
****
この本に載っていた。
小西達夫.タロイモは語る.東京農大出版会,p68
****

|Wolffia globosa
|ミジンコウキクサ
|ミジンコウキクサは、0.3–1.5mm程度の水面に浮かぶ非常に小さい植物でタイなどでは昔から食べられてきた。

増やしやすくタンパク質をはじめとした栄養が豊富なため次世代の食品の材料として注目を浴びている。

|Lasia spinosa
|ミズヤツデ
|インドネシアなど東南アジアの一部地域では葉柄をよく火にかけて毒抜きすることで野菜として食べる。

Lasia属は葉柄に針がたくさんあるので事前に取る必要があると思う。

|Monstera deliciosa
|モンステラ
|モンステラは時折花を咲かせて大型の実を付ける。その実は食べる事ができる。

実は意外と美味しいらしく、栽培されている例がいくつかある。

[.inline-quote]
.参考にしたもの
****
パラグアイの件
小西達夫.タロイモは語る.東京農大出版会,p119

食べている人の動画
https://www.youtube.com/watch?v=YiusjuScq_8
****

|*Xanthosoma sagittifolium*
|アメリカサトイモ
ヤバネサトイモ
ムラサキヤバネイモ
|日本ではあまり知られていないが世界で二番目に食用栽培されているサトイモ科植物。
Colocasia esculentaに比べて、乾燥した土壌を得意とする。
沖縄でも栽培されているらしい。

主に芋の部分を食用にする.

|Lysichiton americanus
|スカンクキャベツ
|まだあまり調べていないけど、アメリカ先住民が救荒食物として食べていたらしい。

|===

== 食用にされている可能性がありそうな種についてのメモ

[%autowidth]
|===
|名|概要

|Arum
|Arumはヨーロッパで一般的な植物で薬にされていたこという話がある。なので食べていたのではないかと思う。

|シマクワズイモ
|シマクワズイモは有史以前に人為的に作られた種だと考えられていてさまざまな地域に導入されているので食用にされていたかもしれない。

|Steudnera
|Steudneraは中国の方で漢方製品が作られているように見えるので食用にされているかもしれない。がColocasiaのシノニムとしてSteudneraという名前が使われているだけかもしれない。

|Colocasia affinus
|タロイモは語る p76
この本以外の情報を探し中

|Homalomena
|タロイモは語る p68
この本以外の情報を探し中

|Schsmatoglottis
|タロイモは語る p68
この本以外の情報を探し中

|Alocasia brancifoli
|タロイモは語る p98
この本以外の情報を探し中

|===
